### ISSUE TITLE
Prepare to support 0.2.0, TinkerPop 3.2.6

### ISSUE THREAD

**Issue by amcp** [awslabs/dynamodb-janusgraph-storage-backend#226]

**Comment by amcp** [comment]
upcoming 0.2.0 supported TP version is 3.2.6
https://github.com/JanusGraph/janusgraph/blob/master/pom.xml#L68

**Comment by bogumil** [comment]
@amcp I would like to ask when support for JanusGraph 0.2.0 could be officially added?

**Comment by hampld** [comment]
@amcp will 0.2.0 be supported any time soon? this would be super awesome

**Comment by DeanWookey** [comment]
@amcp Thanks 👍

**Comment by amcp** [comment]
@DeanWookey @hampld @bogumil I released 0.2.0 support this week. Happy Tinkering!
