### ISSUE TITLE
Support for Apache Tinkerpop 3.2.5

### ISSUE THREAD

**Issue by arunkpatra** [awslabs/dynamodb-janusgraph-storage-backend#228]
Any timelines for upgrading to Tinkerpop 3.25? Will a PR be welcome?

**Comment by amcp** [comment]
I've already got one here, and all we need to do is wait for JanusGraph to do the 0.2.0 release.

**Comment by amcp** [comment]
#225

**Comment by amcp** [comment]
Duplicate of #226
