### ISSUE TITLE
README.md - some missing instructions

### ISSUE THREAD

**Issue by martin-flower** [awslabs/dynamodb-janusgraph-storage-backend#229]
Hello, I'm new to AWS, and to JanusGraph. Working through the instructions in README.md, I have made the following changes.

After step 1, clone repository:
cd ~
git clone https://github.com/awslabs/dynamodb-janusgraph-storage-backend.git 

**Load the Graph of the Gods:**

mvn clean
rm -rf server

I was then able to execute all the queries

**Comment by amcp** [comment]
resolved in 385fe057e61adf19e67964a143e3cda47034bafd
