### ISSUE TITLE
Why Aws passed from Titan to Janusgraph 

### ISSUE THREAD

**Issue by gkhanacer** [awslabs/dynamodb-janusgraph-storage-backend#234]
I am confused. I need a graph database and I want to integrate on aws. I read [it](https://aws.amazon.com/nosql/graph/), it mention about titan, but link about JanusGraph. AWS doesnt support Titan anymore? Or, why aws chose janusgraph?

**Comment by biniama** [comment]
I was also confused at first.
What I found out is: TitanDB was sold to different company and the license changed from open source to commercial.
Then, JanusGraph is born as a fork of the TitanDB and with Apache license.

You can read about the history at https://www.slideshare.net/ptgoetz/large-scale-graph-analytics-with-janusgraph

AWS also mentions that: "Titan project has been superseded by ... JanusGraph project"
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.html

**Comment by amcp** [comment]
JanusGraph is on the upgrade path for Titan. All released versions of JanusGraph are wire compatible with Titan 1.0.0 on the storage backend side - all that is needed is a config override on the JanusGraph side to [use the titan_ids table as opposed to the janusgraph_ids table](http://docs.janusgraph.org/latest/config-ref.html#_ids).

**Comment by mikcaweb** [comment]
JanusGraph is a fork of TitanDB since it was purchased by DataStax.

https://opensource.googleblog.com/2017/01/janusgraph-connects-past-and-future-of-titan.html
