### ISSUE TITLE
Support for WsAndHttpChannelizer or health check using TCP

### ISSUE THREAD

**Issue by monali01** [awslabs/dynamodb-janusgraph-storage-backend#236]
Tinkerpop 3.2.6 added support for WsAndHttpChannelizer, when will we be able to use that here? I need to use HTTP to do the health check on AWS Load balancer and I am using web socket for rest of the gremlin communication. 

Please suggest if there is a way to health check with the TCP now or any alternatives. 

https://stackoverflow.com/questions/46505790/gremlin-server-health-check-endpoint-for-aws-elb

**Comment by amcp** [comment]
JanusGraph 0.2.0 is being released as we speak. JG 0.2.0 supports TinkerPop 3.2.6 so you will be able to take advantage of the WsAndHttpChannelizer.
