### ISSUE TITLE
Migrating titan-1.0.0 to janus-0.1.1

### ISSUE THREAD

**Issue by sunilk747** [awslabs/dynamodb-janusgraph-storage-backend#241]
I am using titan-1.0.0, I want to migrate it to janus-0.1.1. What are the configuration changes I need to do? I also want to reuse the data which was there for titan using janus.

**Comment by amcp** [comment]
@sunilk747 You can set the configuration option `ids.store-name=titan-ids` and update the [classpath of the storage manager class](https://github.com/awslabs/dynamodb-janusgraph-storage-backend/blob/master/src/test/resources/dynamodb.properties#L26). I will add a section to the README.md enumerating the required updates. You will be able to reuse the data you had in your Titan 1.0.0 based tables.
