### ISSUE TITLE
Gremlin Server in EC2 using CloudFormation templates

### ISSUE THREAD

**Issue by rahulbudhrani01** [awslabs/dynamodb-janusgraph-storage-backend#251]
I followed all the steps as mentioned, was able to get the ec2 instance up. Attaching screenshot of the same.
<img width="1043" alt="screen shot 2017-12-08 at 10 20 31 pm" src="https://user-images.githubusercontent.com/26802309/33776021-21ac7c5c-dc66-11e7-9e20-1dc6f57e64ac.png">
 But when I try to access the gremlin server using the output in aws console it says /usr/local/packages/dynamodb-janusgraph-storage-backend-1.1.1/bin/gremlin.sh: No such file or directory.
I am using the dynamodb.properties present in src/test/resources with my region.
Any help in this regard would be appreciated.

**Comment by radupintilie** [comment]
Any update on this? I have the exact same issue, somehow the gremlin install script does not run properly and gremlin is not installed.

**Comment by dvirgiln** [comment]
Any update here?

**Comment by danieljue** [comment]
I can confirm I have the same issues.  I am adjusting the dynamodb-janusgrph-storage-backend-cfn.yaml to see what the problem is.  It might be a java version/maven version issue that causes the install-gremlin-server.sh to fail.

**Comment by danieljue** [comment]
See #260
